var searchData=
[
  ['samesizetupleprefixcomparator',['SameSizeTuplePrefixComparator',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_200_2c_200_20_3e',['SameSizeTuplePrefixComparator&lt; 0, 0 &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator_3_010_00_010_01_4.html',1,'std::tr1::gtest_internal']]],
  ['samesizetupleprefixcomparator_3c_20k_2c_20k_20_3e',['SameSizeTuplePrefixComparator&lt; k, k &gt;',['../structstd_1_1tr1_1_1gtest__internal_1_1SameSizeTuplePrefixComparator_3_01k_00_01k_01_4.html',1,'std::tr1::gtest_internal']]],
  ['scoped_5fptr',['scoped_ptr',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20_3a_3astd_3a_3astringstream_20_3e',['scoped_ptr&lt; ::std::stringstream &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20const_20_3a_3astd_3a_3astring_20_3e',['scoped_ptr&lt; const ::std::string &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scoped_5fptr_3c_20gtest_5fflag_5fsaver_5f_20_3e',['scoped_ptr&lt; GTEST_FLAG_SAVER_ &gt;',['../classtesting_1_1internal_1_1scoped__ptr.html',1,'testing::internal']]],
  ['scopedfaketestpartresultreporter',['ScopedFakeTestPartResultReporter',['../classtesting_1_1ScopedFakeTestPartResultReporter.html',1,'testing']]],
  ['scopedprematureexitfile',['ScopedPrematureExitFile',['../classtesting_1_1internal_1_1ScopedPrematureExitFile.html',1,'testing::internal']]],
  ['scopedtrace',['ScopedTrace',['../classtesting_1_1internal_1_1ScopedTrace.html',1,'testing::internal']]],
  ['sequencetestinglistener',['SequenceTestingListener',['../classSequenceTestingListener.html',1,'']]],
  ['setuptestcasetest',['SetUpTestCaseTest',['../classtesting_1_1SetUpTestCaseTest.html',1,'testing']]],
  ['singlefailurechecker',['SingleFailureChecker',['../classtesting_1_1internal_1_1SingleFailureChecker.html',1,'testing::internal']]],
  ['stack',['Stack',['../classStack.html',1,'']]],
  ['staticasserttypeeqhelper',['StaticAssertTypeEqHelper',['../structtesting_1_1internal_1_1StaticAssertTypeEqHelper.html',1,'testing::internal']]],
  ['staticasserttypeeqhelper_3c_20t_2c_20t_20_3e',['StaticAssertTypeEqHelper&lt; T, T &gt;',['../structtesting_1_1internal_1_1StaticAssertTypeEqHelper_3_01T_00_01T_01_4.html',1,'testing::internal']]],
  ['staticasserttypeeqtesthelper',['StaticAssertTypeEqTestHelper',['../classStaticAssertTypeEqTestHelper.html',1,'']]],
  ['streamableinglobal',['StreamableInGlobal',['../classStreamableInGlobal.html',1,'']]],
  ['streamabletemplateinfoo',['StreamableTemplateInFoo',['../classfoo_1_1StreamableTemplateInFoo.html',1,'foo']]],
  ['string',['String',['../classtesting_1_1internal_1_1String.html',1,'testing::internal']]],
  ['student',['Student',['../classStudent.html',1,'']]],
  ['subprocess',['Subprocess',['../classgtest__test__utils_1_1Subprocess.html',1,'gtest_test_utils']]],
  ['subversionvcs',['SubversionVCS',['../classupload_1_1SubversionVCS.html',1,'upload']]],
  ['successfultest',['SuccessfulTest',['../classSuccessfulTest.html',1,'']]]
];
